const $=s=>document.querySelector(s),canvas=$("#canvas"),ctx=canvas.getContext("2d");
let myId=null,sessionToken=null,room=null,state=null,input={up:false,down:false,left:false,right:false},soundOn=true,particles=[],lastScores={};
const stars=Array.from({length:190},()=>({x:Math.random()*1000,y:Math.random()*600,r:Math.random()*1.3+.2,a:Math.random()*.6+.15,p:Math.random()*6}));
const asteroids=Array.from({length:20},()=>({x:Math.random()*1000,y:Math.random()*600,r:Math.random()*13+5,a:Math.random()*6,vx:-(Math.random()*10+4),vy:(Math.random()-.5)*3}));

function name(){return($("#name").value.trim()||"Minahil").slice(0,18)}
function tone(f=520){if(!soundOn)return;try{let A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.08);o.stop(a.currentTime+.09)}catch(e){}}
async function api(url,data){let r=await fetch(url,{method:data?"POST":"GET",headers:data?{"Content-Type":"application/json"}:{},body:data?JSON.stringify(data):undefined});let j=await r.json();if(!r.ok&&!j.error)j.error="Request failed";return j}
function enter(r){if(!r.ok){$("#error").textContent=r.error;return}myId=r.playerId;sessionToken=r.token;room=r.room;$("#lobby").classList.add("hidden");$("#game").classList.remove("hidden");$("#roomCode").textContent=room;canvas.focus();tone(540);poll()}
$("#create").onclick=async()=>{try{$("#error").textContent="Creating room…";enter(await api("/api/create",{name:name()}))}catch(e){$("#error").textContent="Cannot reach game server."}};
$("#join").onclick=async()=>{try{$("#error").textContent="Joining room…";enter(await api("/api/join",{room:$("#roomInput").value,name:name()}))}catch(e){$("#error").textContent="Cannot reach game server."}};
$("#roomInput").onkeydown=e=>{if(e.key==="Enter")$("#join").click()};
async function poll(){if(!room)return;try{let r=await api(`/api/state?room=${encodeURIComponent(room)}&token=${encodeURIComponent(sessionToken)}`);if(r.ok){let s=r.state;if(state)for(const p of s.players){if((lastScores[p.id]??p.score)<p.score){burst(p.x,p.y,p.id===myId?"#a7d8dc":"#d69aae");tone(p.id===myId?760:420)}lastScores[p.id]=p.score}state=s;ui()}}catch(e){}setTimeout(poll,70)}
function send(){if(room)fetch("/api/input",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({room,token:sessionToken,input})}).catch(()=>{})}
const km={ArrowUp:"up",w:"up",W:"up",ArrowDown:"down",s:"down",S:"down",ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right"};
addEventListener("keydown",e=>{if(km[e.key]&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName)){e.preventDefault();input[km[e.key]]=true;send()}});
addEventListener("keyup",e=>{if(km[e.key]){input[km[e.key]]=false;send()}});
document.querySelectorAll("[data-dir]").forEach(b=>{let d=b.dataset.dir,on=e=>{e.preventDefault();input[d]=true;send()},off=e=>{e.preventDefault();input[d]=false;send()};b.onpointerdown=on;b.onpointerup=off;b.onpointercancel=off;b.onpointerleave=off});
function ui(){if(!state)return;let me=state.players.find(p=>p.id===myId),them=state.players.find(p=>p.id!==myId);$("#roomCode").textContent=state.room;let rm=$("#roomCodeMirror");if(rm)rm.textContent=state.room;$("#myScore").textContent=me?.score??0;$("#theirScore").textContent=them?.score??0;$("#meName").textContent=(me?.name||"MINAHIL").toUpperCase();$("#themName").textContent=(them?.name||"WAITING").toUpperCase();let o=$("#overlay");if(state.status==="waiting")o.innerHTML=`<div class="card"><h2>Awaiting your rival</h2><p>Share room code <b>${state.room}</b>.<br>Join from any second device using this same website.</p></div>`;else if(state.status==="countdown"){let n=Math.max(1,Math.ceil((state.countdownUntil-Date.now())/1000));o.innerHTML=`<div class="card"><h2>${n}</h2><p>Follow the stars.</p></div>`}else if(state.status==="finished"){let w=state.winner?.id===myId;o.innerHTML=`<div class="card"><h2>${w?"The sector is yours.":"Your rival claimed the sector."}</h2><p>${w?"Ten cores collected.":`${state.winner?.name||"Opponent"} reached ten first.`}</p><button id="again">PLAY AGAIN</button></div>`;$("#again").onclick=async()=>{await api("/api/rematch",{room,token:sessionToken})}}else o.innerHTML=""}
setInterval(()=>{if(state?.status==="countdown")ui()},180);
window.addEventListener("blur",()=>{input={up:false,down:false,left:false,right:false};send()});
function burst(x,y,c){for(let i=0;i<25;i++){let a=Math.random()*7,s=Math.random()*3+1;particles.push({x,y,dx:Math.cos(a)*s,dy:Math.sin(a)*s,l:1,c})}}
function ship(x,y,mine){ctx.save();ctx.translate(x,y);let c=mine?"#9ccbd3":"#d69aad";ctx.shadowBlur=18;ctx.shadowColor=c;ctx.fillStyle="#17131d";ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-27);ctx.lineTo(20,17);ctx.lineTo(7,12);ctx.lineTo(0,23);ctx.lineTo(-7,12);ctx.lineTo(-20,17);ctx.closePath();ctx.fill();ctx.stroke();let g=ctx.createLinearGradient(0,15,0,48);g.addColorStop(0,c);g.addColorStop(1,"#0000");ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-6,16);ctx.lineTo(0,48+Math.random()*6);ctx.lineTo(6,16);ctx.fill();ctx.restore()}
function draw(){requestAnimationFrame(draw);let t=performance.now()/1000;ctx.clearRect(0,0,1000,600);let bg=ctx.createRadialGradient(500,260,20,500,300,650);bg.addColorStop(0,"#241628");bg.addColorStop(.4,"#0b0b17");bg.addColorStop(1,"#03040a");ctx.save();ctx.globalAlpha=.20;ctx.save();ctx.globalAlpha=.30;ctx.fillStyle=bg;ctx.fillRect(0,0,1000,600);ctx.restore();ctx.restore();

let ag=ctx.createLinearGradient(0,0,1000,250);ag.addColorStop(0,"#67536a00");ag.addColorStop(.25,"#94617b35");ag.addColorStop(.55,"#74538b32");ag.addColorStop(.75,"#59837b28");ag.addColorStop(1,"#0000");ctx.fillStyle=ag;ctx.beginPath();ctx.moveTo(0,65);for(let x=0;x<=1000;x+=40)ctx.lineTo(x,90+Math.sin(t*.7+x*.012)*50);ctx.lineTo(1000,230);ctx.lineTo(0,210);ctx.fill();
for(const s of stars){let sx=(s.x-t*(4+s.r*5)+1100)%1100-50;ctx.globalAlpha=s.a*(.65+.35*Math.sin(t+s.p));ctx.fillStyle="#f6e8e3";ctx.beginPath();ctx.arc(sx,s.y+Math.sin(t*.25+s.p)*2,s.r,0,7);ctx.fill()}ctx.globalAlpha=1;
ctx.save();ctx.translate(150,130);let pg=ctx.createRadialGradient(-20,-20,3,0,0,85);pg.addColorStop(0,"#8b7079");pg.addColorStop(.5,"#2a222d");pg.addColorStop(1,"#0d0b12");ctx.fillStyle=pg;ctx.beginPath();ctx.arc(0,0,78,0,7);ctx.fill();ctx.strokeStyle="#b5897a55";ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,0,130,20,-.2,0,7);ctx.stroke();ctx.restore();
for(const a of asteroids){a.x+=a.vx/60;a.y+=a.vy/60;if(a.x<-40)a.x=1040;if(a.y<-40)a.y=640;if(a.y>640)a.y=-40;ctx.save();ctx.translate(a.x,a.y);ctx.rotate(t*.18+a.a);ctx.fillStyle="#17131a";ctx.strokeStyle="#5c454d";ctx.beginPath();for(let i=0;i<8;i++){let q=i*Math.PI/4,r=a.r*(.7+Math.sin(i*2.3+a.a)*.2);i?ctx.lineTo(Math.cos(q)*r,Math.sin(q)*r):ctx.moveTo(Math.cos(q)*r,Math.sin(q)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
if(state){let o=state.orb;ctx.save();ctx.translate(o.x,o.y+Math.sin(t*2.1)*5);ctx.scale(1+Math.sin(t*2.6)*.06,1+Math.sin(t*2.6)*.06);ctx.rotate(t*.7);ctx.shadowBlur=28;ctx.shadowColor="#d9a1bd";ctx.strokeStyle="#d8adad";ctx.lineWidth=1.5;for(let i=0;i<3;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.ellipse(0,0,30,10,0,0,7);ctx.stroke()}ctx.fillStyle="#f1ddd5";ctx.beginPath();for(let i=0;i<10;i++){let a=-Math.PI/2+i*Math.PI/5,r=i%2?7:17;i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.restore();state.players.forEach(p=>{let mine=p.id===myId;ship(p.x,p.y,mine);ctx.textAlign="center";ctx.font="11px Georgia";ctx.fillStyle=mine?"#b8d7d7":"#ddb2bd";ctx.fillText(mine?(p.name||"You"):p.name,p.x,p.y-37)})}
for(const p of particles){p.x+=p.dx;p.y+=p.dy;p.l-=.025;ctx.globalAlpha=Math.max(0,p.l);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,2,2)}ctx.globalAlpha=1;particles=particles.filter(p=>p.l>0)}
draw();